inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Lint/Debugger:
  Enabled: true