default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= (ENV.fetch('RAILS_MAX_THREADS') { 5 }).to_i * (ENV.fetch('WEB_CONCURRENCY') { 1 }).to_i %>

local_connection: &local_connection
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  <<: *local_connection
  database: rails_genius_development

test:
  <<: *default
  <<: *local_connection
  database: rails_genius_test

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
